services:
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        ports:
            - 8001:8001
            - 8002:8002
        depends_on:
            - app
        init: true
        environment:
            TZ: Asia/Tokyo

    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        volumes:
            - ./app:/root/app
            - ./common:/root/common
        tty: true
        environment:
            TZ: Asia/Tokyo

    admin:
        build:
            context: .
            dockerfile: ./docker/admin/Dockerfile
        volumes:
            - ./admin:/root/admin
            - ./seeder:/root/admin/seeder
            - ./common:/root/common
        tty: true
        environment:
            TZ: Asia/Tokyo

    tailwind:
        build:
            context: .
            dockerfile: ./docker/tailwind/Dockerfile
        volumes:
            - ./admin:/root/admin
        tty: true
        command: npx tailwindcss -i /root/admin/static/style.css -o /root/admin/static/dist.css --watch
    db:
        image: mysql:8.3.0
        ports:
            - 13306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: blog
            TZ: Asia/Tokyo
